### ISSUE TITLE
Evaluate version of Python to be used in 2.0

### ISSUE THREAD

**Issue by HeroesLament** [FreeTAKTeam/FreeTakServer#362]
Major new features of the 3.11 series, compared to 3.10
Among the new major new features and changes so far:

PEP 657 – Include Fine-Grained Error Locations in Tracebacks
PEP 654 – Exception Groups and except*
PEP 673 – Self Type
PEP 646 – Variadic Generics
PEP 680 – tomllib: Support for Parsing TOML in the Standard Library
PEP 675 – Arbitrary Literal String Type
PEP 655 – Marking individual TypedDict items as required or potentially-missing
bpo-46752 – Introduce task groups to asyncio
PEP 681 – Data Class Transforms
bpo-433030– Atomic grouping ((?>…)) and possessive quantifiers (*+, ++, ?+, {m,n}+) are now supported in regular expressions.
The Faster Cpython Project is already yielding some exciting results. Python 3.11 is up to 10-60% faster than Python 3.10. On average, we measured a 1.22x speedup on the standard benchmark suite. See Faster CPython for details.
(Hey, fellow core developer, if a feature you find important is missing from this list, let Pablo know.)
The next pre-release of Python 3.11 will be 3.11.0b5, currently scheduled for Monday, 2022-07-25.

**Comment by HeroesLament** [comment]
Need to check major differences between 3.10 and 3.11 to see which python version to standardize on.

**Comment by naman108** [comment]
any progress so far?

**Comment by brothercorvo** [comment]
Python 3.11 is claimed to be up  to 64% faster than 3.10

![Image](https://user-images.githubusercontent.com/60719165/194580285-519d8c3f-9bd7-4d86-a90e-f8d74d8c9b75.png)

**Comment by brothercorvo** [comment]
Differences of versions since 3.8:

## 3.9 New syntax features:

[PEP 584](https://www.python.org/dev/peps/pep-0584), union operators added to dict;

[PEP 585](https://www.python.org/dev/peps/pep-0585), type hinting generics in standard collections;

[PEP 614](https://www.python.org/dev/peps/pep-0614), relaxed grammar restrictions on decorators.

New built-in features:

[PEP 616](https://www.python.org/dev/peps/pep-0616), string methods to remove prefixes and suffixes.

New features in the standard library:

[PEP 593](https://www.python.org/dev/peps/pep-0593), flexible function and variable annotations;

[os.pidfd_open()](https://docs.python.org/release/3.10.7/library/os.html#os.pidfd_open) added that allows process management without races and signals.

## 3.9 Interpreter improvements:

[PEP 573](https://www.python.org/dev/peps/pep-0573), fast access to module state from methods of C extension types;

[PEP 617](https://www.python.org/dev/peps/pep-0617), CPython now uses a new parser based on PEG;

a number of Python builtins (range, tuple, set, frozenset, list, dict) are now sped up using [PEP 590](https://www.python.org/dev/peps/pep-0590) vectorcall;

garbage collection does not block on resurrected objects;

a number of Python modules (_abc, [audioop](https://docs.python.org/release/3.10.7/library/audioop.html#module-audioop), _bz2, _codecs, _contextvars, _crypt, _functools, _json, _locale, [math](https://docs.python.org/release/3.10.7/library/math.html#module-math), [operator](https://docs.python.org/release/3.10.7/library/operator.html#module-operator), [resource](https://docs.python.org/release/3.10.7/library/resource.html#module-resource), [time](https://docs.python.org/release/3.10.7/library/time.html#module-time), _weakref) now use multiphase initialization as defined by PEP 489;

a number of standard library modules ([audioop](https://docs.python.org/release/3.10.7/library/audioop.html#module-audioop), [ast](https://docs.python.org/release/3.10.7/library/ast.html#module-ast), [grp](https://docs.python.org/release/3.10.7/library/grp.html#module-grp), _hashlib, [pwd](https://docs.python.org/release/3.10.7/library/pwd.html#module-pwd), _posixsubprocess, [random](https://docs.python.org/release/3.10.7/library/random.html#module-random), [select](https://docs.python.org/release/3.10.7/library/select.html#module-select), [struct](https://docs.python.org/release/3.10.7/library/struct.html#module-struct), [termios](https://docs.python.org/release/3.10.7/library/termios.html#module-termios), [zlib](https://docs.python.org/release/3.10.7/library/zlib.html#module-zlib)) are now using the stable ABI defined by PEP 384.

## 3.9 New library modules:

[PEP 615](https://www.python.org/dev/peps/pep-0615), the IANA Time Zone Database is now present in the standard library in the [zoneinfo](https://docs.python.org/release/3.10.7/library/zoneinfo.html#module-zoneinfo) module;

an implementation of a topological sort of a graph is now provided in the new [graphlib](https://docs.python.org/release/3.10.7/library/graphlib.html#module-graphlib) module.

## 3.9  Release process changes:

[PEP 602](https://www.python.org/dev/peps/pep-0602), CPython adopts an annual release cycle.

**Comment by brothercorvo** [comment]
# 3.10 changes

## 3.10  features:

[PEP 634](https://www.python.org/dev/peps/pep-0634), Structural Pattern Matching: Specification

[PEP 635](https://www.python.org/dev/peps/pep-0635), Structural Pattern Matching: Motivation and Rationale

[PEP 636](https://www.python.org/dev/peps/pep-0636), Structural Pattern Matching: Tutorial

[bpo-12782](https://bugs.python.org/issue?@action=redirect&bpo=12782), Parenthesized context managers are now officially allowed.

## 3.10  New features in the standard library:

[PEP 618](https://www.python.org/dev/peps/pep-0618), Add Optional Length-Checking To zip.

## 3.10  Interpreter improvements:

[PEP 626](https://www.python.org/dev/peps/pep-0626), Precise line numbers for debugging and other tools.

## 3.10  New typing features:

[PEP 604](https://www.python.org/dev/peps/pep-0604), Allow writing union types as X | Y

[PEP 613](https://www.python.org/dev/peps/pep-0613), Explicit Type Aliases

[PEP 612](https://www.python.org/dev/peps/pep-0612), Parameter Specification Variables

Important deprecations, removals or restrictions:

[PEP 644](https://www.python.org/dev/peps/pep-0644), Require OpenSSL 1.1.1 or newer

[PEP 632](https://www.python.org/dev/peps/pep-0632), Deprecate distutils module.

[PEP 623](https://www.python.org/dev/peps/pep-0623), Deprecate and prepare for the removal of the wstr member in PyUnicodeObject.

[PEP 624](https://www.python.org/dev/peps/pep-0624), Remove Py_UNICODE encoder APIs

[PEP 597](https://www.python.org/dev/peps/pep-0597), Add optional EncodingWarning

**Comment by brothercorvo** [comment]
Check out all the [requirements]( 
https://github.com/FreeTAKTeam/FreeTakServer/blob/c9f33b8e7e65576ad5bb569c2e4b8a606989e7cf/setup.py)
using compatibility Library

**Comment by brothercorvo** [comment]
check out FTS dependencies here:
https://github.com/FreeTAKTeam/FreeTakServer/network/dependencies

**Comment by brothercorvo** [comment]
see https://jott.live/markdown/py3.11_vs_3.8

**Comment by brothercorvo** [comment]
Decision to go for Python 3.11
